### ISSUE TITLE
How are you calling it?

### ISSUE THREAD

**Issue by wcooper90** [chrisspen/punctuator2#4]
How are you calling it?

_Originally posted by @chrisspen in https://github.com/chrisspen/punctuator2/issues/3#issuecomment-713890988_

Hi Chris, 

We've tried:
text = pytesseract.image_to_string(img).encode('latin-1', 'ignore')

As well as executing from the command line and then reading it from a file: 

os.system("tesseract -l eng /var/app/current/inputs/" + str(i) + ".png text")

Thanks for getting back so quickly.

**Comment by chrisspen** [comment]
Please post comments under the original issue. You don't need to create a new issue for new comments.
