### ISSUE TITLE
AssertionError: Model None does not exist

### ISSUE THREAD

**Issue by Mohit54720** [chrisspen/punctuator2#6]
I am getting below error while executing the code
p = Punctuator('INTERSPEECH-T-BRNN-pre.pcl')

AssertionError: Model None does not exist

Detailed Error:
C:\ProgramData\Anaconda3\lib\site-packages\punctuator\punc.py in __init__(self, model_file, use_pauses)
    177 
    178         model_file = self.model_exists(model_file)
--> 179         assert model_file, 'Model %s does not exist.' % model_file
    180 
    181         self.model_file = model_file

AssertionError: Model None does not exist.

**Comment by chrisspen** [comment]
I'm not sure what you expect me to do about this. The model file has to exist at the path you specify.

Closing, since this isn't a bug or anything I can address. Feel free to comment if there's some sort of bug in how to file path is resolved, that isn't working as expected.
