### ISSUE TITLE
not able to install punctuator2 library in Mac m1.

### ISSUE THREAD

**Issue by ghostpacketload** [chrisspen/punctuator2#7]
I am using this library in Mac intel chip. and everything work fine for me.
When I update my system and try to install this library in new Mac M1 it's throw error. 
I am new in python. Please help me.

  ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-install-wyoslhsx/numpy_dddb7fa28a3049d0a6f1f98813557aee/setup.py'"'"'; __file__='"'"'/private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-install-wyoslhsx/numpy_dddb7fa28a3049d0a6f1f98813557aee/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-record-l4o0vkxn/install-record.txt --single-version-externally-managed --prefix /private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-build-env-_rwtp71z/overlay --compile --install-headers /private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-build-env-_rwtp71z/overlay/include/python3.8/numpy Check the logs for full command output.
  
  
  ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-install-o3xh3hbc/scipy_404711783095485b99eb6cdcc92d9b05/setup.py'"'"'; __file__='"'"'/private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-install-o3xh3hbc/scipy_404711783095485b99eb6cdcc92d9b05/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1z/b8__0s5x5198lhpnjw4st7k00000gn/T/pip-record-634zzfvs/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/pawankumar/Library/Python/3.8/include/python3.8/scipy Check the logs for full command output.

**Comment by ghostpacketload** [comment]
Hi finally I found I way to run this library on Mac m1
run these command and you good to go 

brew install --cask miniforge
conda init zsh
conda activate
conda install numpy scipy scikit-learn

and then install the library
pip3 install punctuator

**Comment by chrisspen** [comment]
Thanks for the fix. Closing since the problem seems to be platform specific, for which there's not a solution.
